import os

ITEMS_PER_PAGE = 10

DATABASE_URL = os.environ.get('DATABASE_URL')
DATABASE_NAME = os.environ.get('DATABASE_NAME')
TEST_DATABASE_NAME = os.environ.get('TEST_DATABASE_NAME')
SQLALCHEMY_DATABASE_URI = DATABASE_URL + DATABASE_NAME
SQLALCHEMY_TEST_DATABASE_URI = DATABASE_URL + TEST_DATABASE_NAME
